# ~/.config/starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

right_format = """Last run: $character$cmd_duration"""

format = '''
$time $directory $nodejs$python$rust$golang$git_branch$git_status
[➜](bold #e0af68) '''

[character]
error_symbol = "[✖](bold #f7768e) "
success_symbol = '[✔](bold #7dcfff)'

[cmd_duration]
style = "bold #e0af68"
min_time = 1
format = "[$duration]($style)"

[localip]
ssh_only = false
format = '[$localipv4](bold red) '
disabled = false

[time]
style = "bold #c0caf5"
time_format = "%T"
format = "[$time]($style)"
disabled = false

[username]
show_always = true
format = '[$user]($style) '

[directory]
style = "bold #73daca"
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
format = "on [$symbol$branch]($style) "
symbol = "🌿 "
style = "bold #e0af68"

[git_status]
conflicted = "⚔️ "
ahead = "🏎️ 💨×${count} "
behind = "🐢×${count} "
diverged = "🔱 🏎️ 💨×${ahead_count} 🐢×${behind_count} "
untracked = "🛤️×${count} "
stashed = "📦 "
modified = "📝×${count} "
staged = "🗃️ ×${count} "
renamed = "📛×${count} "
deleted = "🗑️×${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[nodejs]
format = "$symbol$version"
style = "bold"

[python]
format = "[$symbol$version]($style) "
style = "bold #7dcfff"

[rust]
format = "[$symbol$version]($style) "
style = "bold #7dcfff"

[golang]
format = "[$symbol$version]($style) "
style = "bold #7dcfff"
